services:
  - type: web
    name: elixir-toy-app-backend
    env: elixir
    rootDir: backend
    buildCommand: mix deps.get && mix compile && mix ecto.migrate
    preDeployCommand: MIX_ENV=prod mix ecto.migrate
    startCommand: mix phx.server
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: elixir_toy_app_db   # must exactly match your existing Render DB name
          property: connectionString
      - key: SECRET_KEY_BASE
        generateValue: true
